### ISSUE TITLE
Contribute code as PR for review

### ISSUE THREAD

**Issue by gaborbernat** [sphinx-contrib/towncrier#2]
I'd expect the first batch to be a PR so can comment on the code inline 🤔

**Comment by webknjaz** [comment]
Well, I was just moving some history mostly "as is" from the pylibssh repo but feel free to just tell if something is missing via issues. I think all of the following changes will be submitted as PRs. In i's current state, you cannot easily test it anyway, because of the missing CI and packaging bits.

Also, have you checked https://tox--1640.org.readthedocs.build/en/1640/changelog.html to see if something is missing visually?

P.S. Feel free to add inline comments in this commit https://github.com/sphinx-contrib/towncrier/commit/9c655f1b9bace0b7ae93c8b8444805847c448074 if you need to.

**Comment by webknjaz** [comment]
I guess this can be considered as answered.
